name: Publish Node.js Package
on:
  release:
    types: [created]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    # Setup .npmrc file to publish to GitHub Packages
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
        registry-url: 'https://npm.pkg.github.com'
    - run: npm install
    - run: npm run create-database
      env:
        FAUNADB_SECRET: ${{ secrets.FAUNADB_SECRET }}
    - run: npm run test-ci
      env:
        FAUNADB_SECRET: ${{ secrets.FAUNADB_SECRET }}
    - run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
